name: Generate Snake-2

on:
  schedule:
    - cron: "0 0 * * *"  # Corre a medianoche UTC todos los días.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.1
        with:
          github_user_name: FRANCISCODANIEL03
          output: dist/snake.svg

      - name: Add & Commit Snake Animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg
          git commit -m "Generate snake animation" || echo "No changes to commit"

      - name: Push to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
